### ISSUE TITLE
Support multi-gpu training?

### ISSUE THREAD

**Issue by jordane95** [voidful/TFkit#10]
Hey, I'm using your framework to train a BART but it exceeds my GPU memory. Does this code support multi-gpu training?

**Comment by voidful** [comment]
It support data parallel(DP) by default, it should be fine with multi-gpu.
For distributed data parallel(DDP), you can try the latest version v0.8.1:

use `whereis tfkit-train` to find the absolute path of excitable python file.
Then `python -m torch.distributed.launch tfkit-train absolute path`

**Comment by jordane95** [comment]
That works well. Thank you!

**Comment by jordane95** [comment]
Another question. I tried your latest version v0.8.1. It works fine on GPU during training (almost 40 min/epoch). But the evaluation using `tfkit-eval` command cost too long (up to 10 h/shot). It seems that the evaluation process is carried out on CPU rather than GPU. Have you oberversed the same problem on your machine?

**Comment by voidful** [comment]
> Another question. I tried your latest version v0.8.1. It works fine on GPU during training (almost 40 min/epoch). But the evaluation using `tfkit-eval` command cost too long (up to 10 h/shot). It seems that the evaluation process is carried out on CPU rather than GPU. Have you oberversed the same problem on your machine?

training sequence generation model will use teaching forcing strategy to train faster.
In evaluation stage, we will auto-regressive decode the result, beside it can not support batch decoding in evaluation stage, it will be much slower.

I am refactoring the prediction pipeline to support batch prediction, stay tuned～
