### ISSUE TITLE
Task types

### ISSUE THREAD

**Issue by oldaandozerskaya** [voidful/TFkit#4]
Hi! Thank you for your great work!

Could you please explain what is the difference between the "once" and "onebyone" task types? Which one is better for summarization?

**Comment by oldaandozerskaya** [comment]
And one more question. How can I restore the model from checkpoint and continue training?

**Comment by voidful** [comment]
once is more like an experimental model, it tries to generate the whole sentence at once. It will be too difficult to learn, therefore the result will be failed usually.
onebyone will generate text one by one in both training and evaluation, the result will be better but slow.

So I recommend you to try clm(causal lm) or seq2seq model. These models mainly combine the advantage from once and onebyone. Keeping a fast training speed and giving a better result on downstream tasks.

You can use seq2seq with Bart for summarization.

**Comment by voidful** [comment]
> And one more question. How can I restore the model from checkpoint and continue training?

you can use:
`tfkit-train --resume model_path`

**Comment by oldaandozerskaya** [comment]
Thank you for your quick answer! 

> You can use seq2seq with Bart for summarization.

I'm going to try this solution. Thank you!

Do you have any publications to learn more about your toolkit?

**Comment by voidful** [comment]
> Thank you for your quick answer!
> 
> > You can use seq2seq with Bart for summarization.
> 
> I'm going to try this solution. Thank you!
> 
> Do you have any publications to learn more about your toolkit?

Sorry for bad documentation.
I will update the document as soon as possible.

**Comment by oldaandozerskaya** [comment]
> 
> 
> > Thank you for your quick answer!
> > > You can use seq2seq with Bart for summarization.
> > 
> > 
> > I'm going to try this solution. Thank you!
> > Do you have any publications to learn more about your toolkit?
> 
> Sorry for bad documentation.
> I will update the document as soon as possible.

No problem, it's ok!

**Comment by voidful** [comment]
> > > Thank you for your quick answer!
> > > > You can use seq2seq with Bart for summarization.
> > > 
> > > 
> > > I'm going to try this solution. Thank you!
> > > Do you have any publications to learn more about your toolkit?
> > 
> > 
> > Sorry for bad documentation.
> > I will update the document as soon as possible.
> 
> No problem, it's ok!

I just update the document and readme. 
Hope this can help.
