### ISSUE TITLE
The purpose of ori_input ?

### ISSUE THREAD

**Issue by zuujhyt** [voidful/TFkit#6]
Hello,

The [add_record method](https://github.com/voidful/TFkit/blob/master/tfkit/utility/eval_metric.py#L68) receives ```ori_input``` as its first argument, and it relates to ```input``` and ```input_list```.
But I didn't see they are used in the ```cal_score``` method, where only prediction and target are used.
Could you explain a little bit about this?
Thanks.

**Comment by voidful** [comment]
Hi

Input would not affect the score calculation indeed. `ori_input` is mainly used for reference on evaluation output.
You can refer to the output file after `tfkit-eval`

**Comment by zuujhyt** [comment]
understand. Thank you!
